# PDF to Markdown Conversion Configuration

margins:
  header_margin: 100
  footer_margin: 100

formatting:
  max_newlines: 2

images:
  output_dir: 'images'
  formats: ['jpg', 'png']
  min_size: 100  # minimum width/height in pixels to save

chunking:
  max_chars: 8000  # ~2000 words, optimal for most LLMs
  overlap_chars: 500  # overlap between chunks to maintain context
  keep_full_file: true  # whether to keep the full markdown file in addition to chunks